version: '3.8'

services:
  app:
    image: social_media_app_image
    container_name: social_media_app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
