"""v_02

Revision ID: 75469fabeabf
Revises: b793e81a0536
Create Date: 2024-04-19 16:56:43.188575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75469fabeabf'
down_revision: Union[str, None] = 'b793e81a0536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
