"""v_04

Revision ID: 92c1c2e45142
Revises: bae7817fb76c
Create Date: 2024-04-22 18:18:29.110692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c1c2e45142'
down_revision: Union[str, None] = 'bae7817fb76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Likesofposts', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('Likesofposts', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('Likesofposts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('Likesofposts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('follower', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('follower', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('follower', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('follower', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('follower', 'updated_at')
    op.drop_column('follower', 'created_at')
    op.drop_column('follower', 'is_deleted')
    op.drop_column('follower', 'is_active')
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'created_at')
    op.drop_column('comments', 'is_deleted')
    op.drop_column('comments', 'is_active')
    op.drop_column('Likesofposts', 'updated_at')
    op.drop_column('Likesofposts', 'created_at')
    op.drop_column('Likesofposts', 'is_deleted')
    op.drop_column('Likesofposts', 'is_active')
    # ### end Alembic commands ###
