"""v_03

Revision ID: bae7817fb76c
Revises: 75469fabeabf
Create Date: 2024-04-22 14:21:41.644666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae7817fb76c'
down_revision: Union[str, None] = '75469fabeabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('follower_user_fkey', 'follower', type_='foreignkey')
    op.create_foreign_key(None, 'follower', 'User', ['followed_to'], ['id'])
    op.create_foreign_key(None, 'follower', 'User', ['following_by'], ['id'])
    op.drop_column('follower', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follower', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'follower', type_='foreignkey')
    op.drop_constraint(None, 'follower', type_='foreignkey')
    op.create_foreign_key('follower_user_fkey', 'follower', 'User', ['user'], ['id'])
    # ### end Alembic commands ###
