"""v_05

Revision ID: c30c57833753
Revises: f5333cec7e66
Create Date: 2024-04-25 16:46:46.999507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c30c57833753'
down_revision: Union[str, None] = 'f5333cec7e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PasswordReset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PasswordReset_email'), 'PasswordReset', ['email'], unique=True)
    op.create_index(op.f('ix_PasswordReset_id'), 'PasswordReset', ['id'], unique=False)
    op.create_index(op.f('ix_PasswordReset_token'), 'PasswordReset', ['token'], unique=True)
    op.drop_index('ix_password_reset_email', table_name='password_reset')
    op.drop_index('ix_password_reset_id', table_name='password_reset')
    op.drop_index('ix_password_reset_token', table_name='password_reset')
    op.drop_table('password_reset')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expiration_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='password_reset_pkey')
    )
    op.create_index('ix_password_reset_token', 'password_reset', ['token'], unique=True)
    op.create_index('ix_password_reset_id', 'password_reset', ['id'], unique=False)
    op.create_index('ix_password_reset_email', 'password_reset', ['email'], unique=True)
    op.drop_index(op.f('ix_PasswordReset_token'), table_name='PasswordReset')
    op.drop_index(op.f('ix_PasswordReset_id'), table_name='PasswordReset')
    op.drop_index(op.f('ix_PasswordReset_email'), table_name='PasswordReset')
    op.drop_table('PasswordReset')
    # ### end Alembic commands ###
